### ISSUE TITLE
[.NET MAUI] connecting intune freezes the app

### ISSUE THREAD

**Issue by MikeP0911** [microsoftconnect/ms-intune-app-sdk-android#196]
# Intune Android App SDK for .NET MAUI Issue

## Summary

As soon as the Microsoft.Intune.Maui.Essentials.android is installed and the the code is written in ONMAMCreate the app freezes on launch.

## Details

- **`Microsoft.Intune.Maui.Essentials.android` Version:**10.0.0-beta
- **Operating System (Mac, Linux, Windows) and Version**: Windows
- **Visual Studio Version**:17.7.6
## Logs

For **build issues**, please include:

- MSBuild Logs
[Output-Debug.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/files/13234252/Output-Debug.txt)

## Questions to Ask Before Submission

1. Does the app build and launch without including the `Microsoft.Intune.Maui.Essentials.android` package? yes
2. Does the issue reproduce if you rebuild after deleting the `bin` and `obj` output folders? yes
3. Have you checked the [.NET MAUI repository](https://github.com/dotnet/maui/issues) for similar issues? If so, please follow the guidance there or add that information to this issue.
4. Are you using the latest `Microsoft.Intune.Maui.Essentials.android` NuGet package version?10.0.0-beta

**Comment by boyzhang-msft** [comment]
Hi @MikeP0911 , thanks for reaching out. Could you please provide this information so we can investigate further?

Company Portal Logs
PowerLift ID:

For guidance, see [Report a problem in Company Portal or Intune app for Android Opens in new window or tab](https://learn.microsoft.com/mem/intune/user-help/send-logs-to-your-it-admin-by-email-android)

**Comment by MikeP0911** [comment]
Hello @boyzhang-msft 

Send the company portal logs.
ID: JZPF564N

**Comment by meghandaly** [comment]
Thank you for the report and information! We will be taking a fix in our SDK to address this and it will be included in a future release!

**Comment by MikeP0911** [comment]
@meghandaly 
Is there any working sample with MAUI and any previous working Intune SDK.. 
This freeze does not happen only in beta 10.0.0 it also happens for 9.5.2-Beta2.

Is there any workaround. Since Xamarin forms life period is going to end and we need to roll out MAUI.

**Comment by meghandaly** [comment]
@MikeP0911 are you developing against .NET 7 or .NET 8?

**Comment by meghandaly** [comment]
@MikeP0911 

Are you also able to share a sample app that replicates the issue? We have internal apps used for testing and we did not encounter this.

Publishing a sample is on our radar, but has yet to be completed.

**Comment by MikeP0911** [comment]
@meghandaly 
We are developing a .NET 7 MAUI application using Microsoft.Intune.Maui.Essentials.android.
Simply by including the SDK the running the project freeze.
We have deleted some of our project related files and given the minimum.


[SampleIntune-MS.zip](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/files/13344603/SampleIntune-MS.zip)

**Comment by MikeP0911** [comment]
@meghandaly 

When can we expect the sample. Since there are no resources about the implementation.

**Comment by MikeP0911** [comment]
@meghandaly 

Please provide us the working sample.

**Comment by meghandaly** [comment]
We will be publishing a sample this month. We appreciate your patience.

**Comment by MikeP0911** [comment]
Thank you. Awaiting the sample.

**Comment by JamestsaiTW** [comment]
> We will be publishing a sample this month. We appreciate your patience.

Hope we can get a sample this month😊

**Comment by Archit-Pikle** [comment]
Hi @JamestsaiTW, you can find the MAUI sample app at https://github.com/msintuneappsdk/ms-intune-app-sdk-android-samples

**Comment by MikeP0911** [comment]
Hi @Archit-Pikle, I have referred your MAUI sample application for intune and trying to do the same with my application, but its throwing the below error:

```
Error		Unsupported TargetFramework net7.0-android33.0
   at Core.Resources.GetInternalMAMSDK(String targetFramework)
   at Core.Mamifier.PrepareClasspath()
   at Core.Mamifier.Mamify()
   at BuildTasks.MamifyFiles.Execute()   
```
I have installed the latest Intune version-10.0.0 as in your sample, but we are using .net7 version only whereas in your sample app I can see its version-8. Is this intune version does not support .net7 version? Please help.

**Comment by Archit-Pikle** [comment]
Hi @MikeP0911 , can you add `net7.0-android` instead of `net7.0-android33.0` in your csproj file and see if that works?

**Comment by MikeP0911** [comment]
> Hi @MikeP0911 , can you add `net7.0-android` instead of `net7.0-android33.0` in your csproj file and see if that works?

Thank you @Archit-Pikle , this helped. Able to install Intune package now without any issues.
