### ISSUE TITLE
REDIST.txt file is missing

### ISSUE THREAD

**Issue by darkbluee1976** [microsoftconnect/ms-intune-app-sdk-android#241]
## Summary
According to 3-b of the license below, we may distribute Distributable Code identified in a REDIST.TXT file.However, since there is no REDIST.TXT file, distributing it would be a violation of the license.
License：
https://github.com/microsoftconnect/ms-intune-app-sdk-android/blob/master/Microsoft%20License%20Terms%20Intune%20App%20SDK%20for%20Android.pdf
Related Issues：https://github.com/microsoftconnect/ms-intune-app-sdk-ios/issues/96

**Expectation:**
Plz added REDIST.txt.

**Comment by kanishkaBagga** [comment]
I am looking into it
