### ISSUE TITLE
Intune Sdk[11.0.0]: Quits app process automatically after calling sdk Api unregisterAccount(upn, aadId) 

### ISSUE THREAD

**Issue by MeghaVai** [microsoftconnect/ms-intune-app-sdk-android#248]
# Intune Android App SDK Policy Enforcement Issue

## Questions to Ask Before Submission

1. Have you completed the exit criteria for each phase in the [Intune App SDK for Android Integration Guide]?
2. Have you checked the [Microsoft Intune App SDK for Android] repository for similar issues?
3. Are you using the latest version of the [SDK]?

## Summary

Each phase of the [Intune App SDK for Android Integration Guide] outlines specific exit criteria for proceeding to subsequent phases.

Please reference the specific exit criteria scenario that is failing.

## Repro Steps

Please provide concrete steps to reproduce the issue you are encountering.

1.

**Expectation:**

**Observation:**

## Details

- **Intune Android App SDK Version:**
- **Android Device Make and Model:**
- **Android Device OS Version:**
- **Android Studio Version:**

### Company Portal Logs

**Incident ID:**

For guidance, see [Report a problem in Company Portal or Intune app for Android].

### Screenshots and Recordings

If screenshots and/or recordings would help explain the behavior, please include them here.

## AndroidX Dependencies

If your app includes any AndroidX libraries, please list them here, along with the version info:

- NA

## Third-Party Library Dependencies

If your app includes any third-party libraries, please list them here, along with the version info:

- NA

[Intune App SDK for Android Integration Guide]: https://learn.microsoft.com/mem/intune/developer/app-sdk-android-phase1
[Report a problem in Company Portal or Intune app for Android]: https://learn.microsoft.com/mem/intune/user-help/send-logs-to-your-it-admin-by-email-android
[Microsoft Intune App SDK for Android]: https://github.com/msintuneappsdk/ms-intune-app-sdk-android
[SDK]: https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases

**Comment by meghandaly** [comment]
Please fill out the template appropriately.
