### ISSUE TITLE
Samsung Devices shows "No Available apps Version with old version" OR "Action Blocked with SDK Version 11.0.0"

### ISSUE THREAD

**Issue by guru2010j** [microsoftconnect/ms-intune-app-sdk-android#251]
# Intune Android App SDK Policy Enforcement Issue

## Questions to Ask Before Submission

1. Have you completed the exit criteria for each phase in the [Intune App SDK for Android Integration Guide]?

**Answer: Yes, The Application was working for 2 to 3 years.**

2. Have you checked the [Microsoft Intune App SDK for Android] repository for similar issues?

**Answer: Yes, Nothing found.**

3. Are you using the latest version of the [SDK]?

**Answer: Yes, Version 11.0.0.**

## Summary

Hello Team,

We started seeing Samsung-specific issues as follows.

1. Install MultiLine for the Intune application which has Intune SDK
2. Company portal installed, Authentication works first time.
3. The MultiLine app is configured and policies are applied.
4. The user can use the application without any issues.

The issue starts when the user Deletes the application and re-installs it.

1. When the MultiLine application is installed and the user opens the application.
2. The Intune SDK somehow collects previously cached policy
3. The application does not ask the user to authenticate or select an account from the company portal
4. The SDK automatically based previous policy asks the user to enter the pin configured in the previous install.
5. If the user enters the same pin, the below error does not allow the MultiLine application to proceed further.

Important:  We started seeing this issue in the last 20 days. it was not there previously. Request your support in this ASAP.

## Details

- **Intune Android App SDK Version:** Version 11.0.0
- **Android Device Make and Model:** Samsung S22, S23 most of Samsung devices
- **Android Device OS Version:** 14
- **Android Studio Version:**  Ladybug or Koala

### Company Portal Logs

**Incident ID:** 2S59ANFB

For guidance, see [Report a problem in Company Portal or Intune app for Android].

### Screenshots and Recordings

![image](https://github.com/user-attachments/assets/6c536c8e-9c21-4a37-8b9b-25277c14514a)
![image](https://github.com/user-attachments/assets/b1b1d3fc-7db1-4b26-8b9e-3a9325d42770)

**Comment by mukeshk-ms** [comment]
@guru2010j - I checked the logs based on the company portal incident id which appears to be for 23rd October. Was the issue reported around same time?

Based on our logs, it appears that there is an app called ["Link to Windows"](https://play.google.com/store/apps/details?id=com.microsoft.appmanager&hl=en) installed on the device, that might be interfering with your LOB app and MAM policy. Can you please check with some of the affected users, if they run into similar issue after disabling the app? 

Also does it happen for all users, only after installing/reinstalling the app or the issue is occurring on Samsung devices that has this app (Link to Windows) preloaded.

**Comment by guru2010j** [comment]
Hi @mukeshk-ms ,

Thank you so much for your response.

I uninstalled the Link to Windows app updates, and after that, the Samsung device started working properly.

I'll check with my customers and let you know if uninstalling the updates resolves the issue for them as well.

In the meantime, do we know why Link to Windows is interacting with the Intune SDK? Are there any plans to address this either from the SDK side or the Link to Windows app side?

![image](https://github.com/user-attachments/assets/d9f21064-a219-43b0-bb3a-153880099a10)

**Comment by mukeshk-ms** [comment]
thanks for confirming @guru2010j. We are currently having internal discussions to explore the possibility of addressing this issue from the SDK side.
