### ISSUE TITLE
[.NET MAUI] Intune currently supports a maximum Xamarin.Android SDK major version of 34. Your major version is 35. Please downgrade your app's target framework.

### ISSUE THREAD

**Issue by gvhung** [microsoftconnect/ms-intune-app-sdk-android#255]
Please update version 11.0.0 on Nuget.

Error when build project with .NET MAUI target Net9.0-android
"Intune currently supports a maximum Xamarin.Android SDK major version of 34. Your major version is 35. Please downgrade your app's target framework."

Thank you verry much.

**Comment by manupa-ms** [comment]
Looking into this.

**Comment by Admin-Saturn-ii** [comment]
Same problem to me. I need to go back from net9.0 to net8.0 for this issue.

**Comment by manupa-ms** [comment]
We are aware of this, and the team is working on the newest release targeting .NET 9. It should be available roughly before end of the year at which time, the NuGet downloads page would also get updated.
