### ISSUE TITLE
App Configuration value returns empty when accessing via Intune SDK

### ISSUE THREAD

**Issue by frpaf** [microsoftconnect/ms-intune-app-sdk-android#256]
# Intune Android App SDK [Gradle Build Plugin] Issue

## Questions to Ask Before Submission

1. Does your app compile and launch successfully without the Intune App SDK? - YES
3. Have you checked the [Microsoft Intune App SDK for Android] repository for similar issues? - YES
4. Are you using the latest version of the [SDK and Plugin]? - YES

## Summary

Please briefly describe the issue you are experiencing.
I use the documentation https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-android-phase3 and have set up a sample project 
1. First set up the root build.gradle with the jar file 
![image](https://github.com/user-attachments/assets/7d92be6a-2805-4d8f-9ac8-6b8c924212f5)
2. Then build.gradle under the app folder 
![image](https://github.com/user-attachments/assets/88826368-ad12-4b09-8ac9-c735e690e5e2)

Here is a link to the repository https://github.com/frpaf/my-app-intune
Once i set up, i am able to access the intune related classes below is my code

![image](https://github.com/user-attachments/assets/4965fe22-da80-4668-9adc-240d6f900899)

I have previously deployed my intune mamasdk enabled app to the playstore via intune and then i build my app open the app i get an empty object array 

![image](https://github.com/user-attachments/assets/831ce63d-2a6e-4679-8709-53ef0fb58d1a)
The Toast message shows empty value. 

I have tried to run the value from old app it displays the values . The difference between the old app and the new app is the old app is a Cordova app and the new App is a expo app (React Native)

Not sure what else i am missing the section com.microsoft.intune.mam.client.app.MAMApplication does not apply as i have the app sub class Application. Thanks in advance

![image](https://github.com/user-attachments/assets/33889ff4-9702-4a6b-8551-10e31fb44560)

This is how it should look on a working version (old cordova) solution

![image](https://github.com/user-attachments/assets/21e1c09d-3f2b-42f2-8f7c-58437737f4c6)

## Details

- **Intune Android App SDK Version:** 11.0.0
- **Gradle Version:** 
- **AGP Version:**
- **Operating System (Mac, Linux, Windows) and Version:** MACOS 
- **Android Studio Version:** LadyBug

## Logs
Please write the output of your Gradle build (with the `--debug` and `--stacktrace` options) to a file and attach it to this issue.
[BuildOutput.pdf](https://github.com/user-attachments/files/17966072/BuildOutput.pdf)

## AndroidX Dependencies

If your app includes any AndroidX libraries, please list them here, along with the version info:

- NA

## Third-Party Library Dependencies

If your app includes any third-party libraries, please list them here, along with the version info:

- NA

[Gradle Build Plugin]: https://learn.microsoft.com/mem/intune/developer/app-sdk-android-phase3#gradle-build-plugin
[enable reporting]: https://learn.microsoft.com/mem/intune/developer/app-sdk-android-phase3#reporting
[Microsoft Intune App SDK for Android]: https://github.com/msintuneappsdk/ms-intune-app-sdk-android
[SDK and Plugin]: https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases

**Comment by HanishaChowdary** [comment]
I'm looking into this

**Comment by frpaf** [comment]
Thanks @HanishaChowdary for your reply. Yes there is a app config policy targeting the app the same app config is used for the other app which shows the values they both have the same bundle Id . Yes the OID is set to empty/null or even with a logged in users OID got from the intune portal still returns an empty object .

**Comment by HanishaChowdary** [comment]
@frpaf can you please share us the code snippet of fetching MAM config from the old app where it is working for reference?
Also, since you mentioned that with logged in user also you see the same behavior, can you please confirm if you tried MAM enrollment first and then fetch MAM config?

**Comment by frpaf** [comment]
Actually i found the issue . The AndroidManifest.xml needs additional meta tag setting .

`<meta-data android:name="android.content.APP_RESTRICTIONS" android:resource="@xml/app_restrictions" />`

<img width="1019" alt="image" src="https://github.com/user-attachments/assets/2e1e67de-74b6-4f80-b630-d32b5edcfa11" />

And this needs to be defined in a res folder xml 

<img width="1633" alt="image" src="https://github.com/user-attachments/assets/2ea4e221-f241-4c13-ba9a-dfe4208aabb1" />


The MainActivity code in kotlin is 

<img width="1627" alt="image" src="https://github.com/user-attachments/assets/30b38450-211c-41db-b4e2-abbbe76b412d" />

Thanks @HanishaChowdary for all the help
